### ISSUE TITLE
Turd, I messsed up, dont commit anything until i say so since i accidently pushed to master instead of a branch. Reverting...

### ISSUE THREAD

**Issue by sumeshir26** [Futura-Py/TimerX#101]

**Comment by im-coder-lg** [comment]
Hmm... Maybe yeah, I'll try it.

**Comment by im-coder-lg** [comment]
Wth @sumeshir26 you too in the swear group? Lol

**Comment by im-coder-lg** [comment]
That's a bit better.

**Comment by im-coder-lg** [comment]
Also @sumeshir26 from now, try using Linux as your dev OS. It has ZSH, which has plugins like git, so you can know which branch you are on before pushing. Just a suggestion - if you want, try using a Raspberry Pi with Ubuntu.

**Comment by im-coder-lg** [comment]
ALright - I'm using Gitpod, it will push to my fork of TimerX, but I could rebase the changes, so plus and minus = zero?

**Comment by sumeshir26** [comment]
im so sorry for ghe disturbance

**Comment by im-coder-lg** [comment]
It's fine, but be careful with git from now! That's why I recommend you use Linux, ZSH with the ohmyzsh plugins.

**Comment by im-coder-lg** [comment]
Also, you really swear?

**Comment by sumeshir26** [comment]
no, i dont like to swear, espesiallay stuff like f***

**Comment by im-coder-lg** [comment]
Yeah, even me.
