### ISSUE TITLE
Bug: Acrylic goes out of the app

### ISSUE THREAD

**Issue by HuyHung1408** [Futura-Py/TimerX#110]
**Describe the bug**
![Screenshot (1)](https://user-images.githubusercontent.com/86362423/170484910-a2248c3f-d8c5-4859-9938-511e4e18df8c.png)

**To Reproduce**
Properly just happens in Windows 10.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 21H2 (19044.1706)

**Comment by not-nef** [comment]
this can be fixed by just disabling mica on windows 10
