### ISSUE TITLE
Add UI For More Settings

### ISSUE THREAD

**Issue by sumeshir26** [Futura-Py/TimerX#50]

**Comment by im-coder-lg** [comment]
Consider adding this to this [project](https://github.com/orgs/TimerX-App/projects/1)?

**Comment by sumeshir26** [comment]
I added it alreaday!

**Comment by not-nef** [comment]
I told you that i will do it after 1.0. Why did you make an issue?

**Comment by sumeshir26** [comment]
No, I just created it to add to the roadmap

**Comment by not-nef** [comment]
Cool

**Comment by im-coder-lg** [comment]
Also, need some help. I made a secret repo only you guys can see(cuz it's private). I am making a profile README and need some text. If you have any ideas, edit that and I'll straighten it out/make it simple. Then once it's ready, we'll change the repo visibility.

**Comment by not-nef** [comment]
Ill look into it when im home (around 5pm Middle european time)

**Comment by im-coder-lg** [comment]
You are outside? If it's school, how the heck did your teachers allow you to chat with us?

**Comment by sumeshir26** [comment]
I guess he is on his school laptop/chromebook. I also used to check GH notifs a while back when I used to live in the US

**Comment by im-coder-lg** [comment]
Wow. I could never do that lol. But make sure the classes are over. I am starting my work now. Enough of slacking for me.

**Comment by not-nef** [comment]
> You are outside? If it's school, how the heck did your teachers allow you to chat with us?

they dont, i use my ipad. im gonna focus on school now, bye
