### ISSUE TITLE
Add Update System

### ISSUE THREAD

**Issue by sumeshir26** [Futura-Py/TimerX#56]
**Is your feature request related to a problem? Please describe.**
Currently, TimerX does not have a update system

**Describe the solution you'd like**
A Update button in the about window in the long run. In the short run, a Upgrade Code can be added to keep config but still update and use the same AppData folder.

**Describe alternatives you've considered**
_None_

**Comment by not-nef** [comment]
Cool idea, gonna add this to my todo list!

**Comment by im-coder-lg** [comment]
Maybe send a daily ping to GitHub for new releases and if it exists, getting the MSI using some module. If we are on Linux or macOS, `wget` must be preinstalled, so we could try using that to get installers.

**Comment by im-coder-lg** [comment]
I'll try making a basic Tk UI on this, don't blame me. I am giving a heads-up that I am installing Replit so that we could make REPLs for repos here. Moreover, this would help others to create REPLs too.

**Comment by im-coder-lg** [comment]
I think I hit a jackpot on this. Maybe this could be my well-worth first feature of the app. Testing on the branch [here](https://github.com/TimerX-App/TimerX-Update-Test/tree/im-coder-lg/simple-gui), if you got something for this, test it and then commit it there.

**Comment by im-coder-lg** [comment]
Wait, why did you assign _me_ of all people?
Alright, I accept it. Now what?

**Comment by sumeshir26** [comment]
I thought you were working on it on the other repo?

**Comment by im-coder-lg** [comment]
I did a simple local test of unifying the update system with the upstream(https://github.com/TimerX-App/TimerX) code. It failed horribly. However, the update window does work. Maybe I need to rewire more of the code to the upstream code, which I am adding now _here_. Kind of like a link, idk how it'd work out.
Can you tell me where you got the Fluent icons? I know you posted it, but I need it now for some more icons.

**Comment by sumeshir26** [comment]
fluenticons.co

**Comment by im-coder-lg** [comment]
Okay... One part of merging succeeded. I am uploading the changes now. Will link the commit to this.

**Comment by im-coder-lg** [comment]
Thanks for the link!

**Comment by im-coder-lg** [comment]
Read description in 34769d3 to run.

**Comment by im-coder-lg** [comment]
Commit not highlighted?

**Comment by im-coder-lg** [comment]
Alright, I'll be frank with you. I don't know what I should do now! Tell me what I should do and I will do it after Republic Day. Till then, our biggest priority is #64.

**Comment by im-coder-lg** [comment]
I'll start a Repl today, @sumeshir26 can you join it? It would be between 9 AM to 10 AM IST.

**Comment by sumeshir26** [comment]
OK, no prob

**Comment by im-coder-lg** [comment]
Starting in 10 minutes, or maybe five, who knows?

**Comment by sumeshir26** [comment]
Ok, logging in...

**Comment by im-coder-lg** [comment]
Did you get any problems? I see you on .replit only

**Comment by sumeshir26** [comment]
Done by #83
