### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by not-nef** [Futura-Py/TimerX#69]

**Comment by sumeshir26** [comment]
We could use these assets:
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAfQAAAH0CAYAAADL1t+KAAAgAElEQVR4Xu3dj3UUR7bAYUQEOANBBDiChyOwnQGO4EEExhHARmA2AvMiMBmYTQAmgyUCeNUw2PyRNN09XV23bn2c47N7jnu6q75b6OcRQrq45RcBAgQIECDQvcBF9zuwAQIECBAgQOCWoDsEBAgQIEAggYCgJxiiLRAgQIAAAUF3BggQIECAQAIBQU8wRFsgQIAAAQKC7gwQIECAAIEEAoKeYIi2QIAAAQIEBN0ZIECAAAECCQQEPcEQbYEAAQIECAi6M0CAAAECBBIICHqCIdoCAQIECBAQdGeAAAECBAgkEBD0BEO0BQIECBAgIOjOAAECBAgQSCAg6AmGaAsECBAgQEDQnQECBAgQIJBAQNATDNEWCBAgQICAoDsDBAgQIEAggYCgJxiiLRAgQIAAAUF3BggQIECAQAIBQU8wRFsgQIAAAQKC7gwQIECAAIEEAoKeYIi2QIAAAQIEBN0ZIECAAAECCQQEPcEQbYEAAQIECAi6M0CAAAECBBIICHqCIdoCAQIECBAQdGeAAAECBAgkEBD0BEO0BQIECBAgIOjOAAECBAgQSCAg6AmGaAsECBAgQEDQnQECBAgQIJBAQNATDNEWCBAgQICAoDsDBAgQIEAggYCgJxiiLRAgQIAAAUF3BggQIECAQAIBQU8wRFsgQIAAAQKC7gwQIECAAIEEAoKeYIi2QIAAAQIEBN0ZIECAAAECCQQEPcEQbYEAAQIECAi6M0CAAAECBBIICHqCIdoCAQIECBAQdGeAAAECBAgkEBD0BEO0BQIECBAgIOjOAAECBAgQSCAg6AmGaAsECBAgQEDQnQECBAgQIJBAQNATDNEWCBAgQICAoDsDBAgQIEAggYCgJxiiLRAgQIAAAUF3BggQIECAQAIBQU8wRFsgQIAAAQKC7gwQIECAAIEEAoKeYIi2QIAAAQIEBN0ZIECAAAECCQQEPcEQbYEAAQIECAi6M0CAAAECBBIICHqCIdoCAQIECBAQdGeAAAECBAgkEBD0BEO0BQIECBAgIOjOAIGBBS4vL++U7X/657L8/+kfvwjsLfBqeuDhcHi594MzPU/QM03TXgjMECgRv18u++ni4uLH8r/T//eLQCSBQzmbL969e/d/Ar9sLIK+zMvVBLoUOL4Tf1A+UP4q4l2OcNRFH96/f//vEvYnowIs2begL9FyLYEOBUrMp5A/FfIOh2fJnwTelrA/LmF/juR6AUF3OggkFZjeld++fftp+UD4MOkWbWs8gVflPP9Qwv52vK2f3rGgnzZyBYHuBErML8u78t/Lwh90t3gLJnCzwPRufYr6hy+k8+sfAUF3GggkE5i+6K3E/I+yrctkW7MdAn8LHKP+EomgOwMEUgoc35n/VTY3/VU0vwhkFvBO/avpeoee+bjb21AC05+ZH9+ZPxhq4zY7ssAU9bv+TP3jERD0kX8r2HsqgXv37v1RPrj9lGpTNkPgtMDLN2/e/HD6svxXCHr+GdvhAALl3fn0jWKmPzf3i8BwAuU/ZH8u79JfDLdxn3IffeT2n1Hg7t2705+b+65vGYdrT3ME3pZ36d/NuTDzNd6hZ56uvQ0hUN6dPzp+45gh9muTBK4SOH7jmWcj6wj6yNO39xQC5d35m7KRyxSbsQkC6wWGf5cu6OsPj1cSaC5w/Dvn06fb/SIwvMDof5Yu6MP/FgDQs0AJ+pPjD1zpeRvWTmATgfJ74fnr169/2eRmHd5E0DscmiUT+CTgi+GcBQJfCAz9aXdB97uBQKcCx+8KN/35uV8ECBwFjt9o5jAiiKCPOHV7TiHgz89TjNEmNhYY+Xu8C/rGh8ntCOwlcPw553/u9TzPIdCDQAn6L6P+3HRB7+GEWiOBKwRK0B8ef0QqHwIE/vmU++MS9CH/Prqg+21AoFMB31Cm08FZdlWB8g79txL0J1UfEvTmgh50MJZF4JSAd+inhPz7EQUEfcSp2zOBzgX8QJbOB2j5VQQEvQqrmxIgUFPg+PPP/1vzGe5NoDcBQe9tYtZLgMAHgfKNZaag38FBgMBHAUF3EggQ6FKgBH36a2sPuly8RROoICDoFVDdkgCB+gL37t17Wj6APar/JE8g0IeAoPcxJ6skQOArAX+O7kgQ+FJA0J0IAgS6FSjv0v8oH8R+6nYDFk5gQwFB3xDTrQgQ2FfAX1/b19vTYgsIeuz5WB0BAicE/BhVR4TARwFBdxIIEOhawI9S7Xp8Fr+hgKBviOlWBAi0EfAV723cPTWWgKDHmofVECCwUsDfS18J52VpBAQ9zShthMDYAse/xjZ9s5n7Y0vY/agCgj7q5O2bQEIBUU84VFuaLSDos6lcSIBADwJT1G/fvv27v5/ew7SscUsBQd9S070IEAgjUML+6OLi4mmYBVkIgcoCgl4Z2O0JEGgnUKJ+v7xb/9/yge5hu1V4MoF9BAR9H2dPIUCgoYCwN8T36N0EBH03ag8iQCCCwPTtYsu79v8pH/welPX4ivgIQ7GGTQQEfRNGNyFAoGeB6bvNlfVP//gVW+BO+bqI38sS78ReZpvVCXobd08lQIAAgQUC/kriaSxBP23kCgIECBBoKCDm8/AFfZ6TqwgQIECggYCYz0cX9PlWriRAgACBHQXEfBm2oC/zcjUBAgQI7CAg5suRBX25mVcQIECAQEUBMV+HK+jr3LyKAAECBCoIiPl6VEFfb+eVBAgQILChgJifhyno5/l5NQECBAhsICDm5yMK+vmG7kCAAAECZwiI+Rl4n71U0LdxdBcCBAgQWCEg5ivQrnmJoG9n6U4ECBAgsEBAzBdgzbhU0GcguYQAAQIEthUQ8209p7sJ+vam7kiAAAECNwiIeZ3jIeh1XN2VAAECBK4QEPN6x0LQ69m6MwECBAh8JiDmdY+DoNf1dXcCBAgQKAJiXv8YCHp9Y08gQIDA0AJivs/4BX0fZ08hQIDAkAJivt/YBX0/a08iQIDAUAJivu+4BX1fb08jQIDAEAJivv+YBX1/c08kQIBAagExbzNeQW/j7qkECBBIKSDm7cYq6O3sPZkAAQKpBMS87TgFva2/pxMgQCCFgJi3H6Ogt5+BFRAgQKBrATGPMT5BjzEHqyBAgECXAmIeZ2yCHmcWVkKAAIGuBMQ81rgEPdY8rIYAAQJdCIh5vDEJeryZWBEBAgRCCwwW80MJ5eOLi4s/Qg+lLE7Qo0/I+ggQIBBIYMCY/1D475Sg/xVoDFcuRdCjT8j6CBAgEERgxJgfyq+y7/uCHuQQXrOMi9jLszoCBAjEERg15tMEBD3OObxuJYIef0ZWSIBAAIGRYy7oAQ7gjCUI+gwklxAgMLbA6DEX9D7Ov6D3MSerJECgkYCYf4T3KfdGB3DBYwV9AZZLCRAYS0DM/5m3oMc/+4Ief0ZWSIBAAwEx/xJd0BscwoWPFPSFYC4nQCC/gJh/O2NBj3/uBT3+jKyQAIEdBcT8amxB3/EQrnyUoK+E8zICBPIJiPn1MxX0+Odd0OPPyAoJENhBQMxvRhb0HQ7hmY8Q9DMBvZwAgf4FxPz0DAX9tFHrKwS99QQ8nwCBpgJiPo9f0Oc5tbxK0FvqezYBAk0FxHw+v6DPt2p1paC3kvdcAgSaCoj5Mn5BX+bV4mpBb6HumQQINBUQ8+X8gr7cbO9XCPre4p5HgEBTATFfxy/o69z2fJWg76ntWQQINBUQ8/X8gr7ebq9XCvpe0p5DgEBTATE/j1/Qz/Pb49WCvoeyZxAg0FRAzM/nF/TzDWvfQdBrC7s/AQJNBcR8G35B38ax5l0EvaauexMg0FRAzLfjF/TtLGvdSdBrybovAQJNBcR8W35B39azxt0EvYaqexIg0FRAzLfnF/TtTbe+o6BvLep+BAg0FRDzOvyCXsd1y7sK+paa7kWAQFMBMa/HL+j1bLe6s6BvJek+BAg0FRDzuvyCXtd3i7sL+haK7kGAQFMBMa/PL+j1jc99gqCfK+j1BAg0FRDzffgFfR/nc54i6OfoeS0BAk0FxHw/fkHfz3rtkwR9rZzXESDQVEDM9+UX9H291zxN0NeoeQ0BAk0FxHx/fkHf33zpEwV9qZjrCRBoKiDmbfgFvY37kqcK+hIt1xIg0FRAzNvxC3o7+7lPFvS5Uq4jQKCpgJg35b8l6G395zxd0OcouYYAgaYCYt6U/8PDBb39DE6tQNBPCfn3BAg0FRDzpvx/P1zQY8zhplUIevwZWSGBYQXEPM7oBT3OLK5biaDHn5EVEhhSQMxjjV3QY83jqtUIevwZWSGB4QTEPN7IBT3eTL5ekaDHn5EVEhhKQMxjjlvQY87l81UJevwZWSGBYQTEPO6oBT3ubD6tTNDjz8gKCQwhIOaxxyzoseczrU7Q48/ICgmkFxDz+CMW9PgzEvT4M7JCAqkFxLyP8Qp6/DkJevwZWSGBtAJi3s9oBT3+rAQ9/oyskEBKATHva6yCHn9egh5/RlZIIJ2AmPc3UkGPPzNBjz8jKySQSkDM+xynoMefm6DHn5EVEkgjIOb9jlLQ489O0OPPyAoJpBAQ877HKOjx5yfo8WdkhQS6FxDz7kd4S9Djz1DQ48/ICgl0LSDmXY/v78ULevw5Cnr8GVkhgW4FxLzb0X2zcEGPP0tBjz8jKyTQpYCYdzm2axct6PHnKejxZ2SFBLoTEPPuRnZywYJ+kqj5BYLefAQWQCCXgJjnmuen3Qh6/LkKevwZWSGBbgTEvJtRLV6ooC8m2/0Fgr47uQcSyCkg5jnn6h16P3MV9H5mZaUEwgqIedjRbLYw79A3o6x2I0GvRuvGBMYQEPNh5nz/4uLir+i7ff/+/W+Hw+FJ9HXWWJ+g11B1TwKDCIj5IIMu2/QOPf6sBT3+jKyQQEgBMQ85lmqLEvRqtJvdWNA3o3QjAuMIiPk4s/60U0GPP3NBjz8jKyQQSkDMQ41jt8UI+m7Uqx8k6KvpvJDAeAJiPt7MvUPvZ+aC3s+srJRAUwExb8rf/OHeoTcfwckFCPpJIhcQICDmzoCgxz8Dgh5/RlZIoKmAmDflD/NwQQ8zimsXIujxZ2SFBJoJiHkz+nAPFvRwI/lmQYIef0ZWSKCJgJg3YQ/7UEEPO5q/Fybo8WdkhQR2FxDz3cnDP1DQw4/olqDHn5EVEthVQMx35e7mYYIef1SCHn9GVkhgNwEx3426uwcJevyRCXr8GVkhgV0ExHwX5m4fIujxRyfo8WdkhQSqC4h5deLuHyDo8Uco6PFnZIUEqgqIeVXeNDcX9PijFPT4M7JCAtUExLwabbobC3r8kQp6/BlZIYEqAmJehTXtTQU9/mgFPf6MrJDA5gJivjlp+hsKevwRC3r8GVkhgU0FxHxTzmFuJujxRy3o8WdkhQQ2ExDzzSiHu5Ggxx+5oMefkRUS2ERAzDdhHPYmgh5/9IIef0ZWSOBsATE/m3D4Gwh6/CMg6PFnZIUEzhIQ87P4vPgoIOjxj4Kgx5+RFRJYLSDmq+m88CsBQY9/JAQ9/oyskMAqATFfxeZF1wgIevyjIejxZ2SFBBYLiPliMi84ISDo8Y+IoMefkRUSWCQg5ou4XDxTQNBnQjW8TNAb4ns0ga0FxHxrUff7JCDo8c+CoMefkRUSmCUg5rOYXLRSQNBXwu34MkHfEdujCNQSEPNasu7rHXo/Z0DQ+5mVlRK4UkDMHYw9BLxD30P5vGcI+nl+Xk2gqYCYN+Uf6uGCHn/cgh5/RlZIwDvzW7cO79+//+FQfjkObQQEvY37kqcK+hIt1xIIIuCdeZBBDLQMQY8/bEGPPyMrJPCFgJg7EC0EBL2F+rJnCvoyL1cTaCog5k35h364oMcfv6DHn5EVEvggIOYOQksBQW+pP+/Zgj7PyVUEmgqIeVN+D//4H5T3Ly4u/oqOUb548rfytZNPoq+zxvoEvYaqexLYUEDMN8R0q9UCgr6abrcXCvpu1B5EYLmAmC8384o6AoJex3XLuwr6lpruRWBDATHfENOtzhYQ9LMJq99A0M8kLof8stzifvnnTvnn7fGf6a5vy5/jvDrz9l4+qICYDzr4wNsW9MDDOS5N0BfOqBzqB+UlD8oXh/xY/neK+RTy6369Lde9fPfu3X/KBc99l6uF2INeLuaDDj74tqc3L+Xj2Zvgy7xVvijul/Kx9nn0ddZYn6DPUJ0+wJbLHh0jPr0bX/WrvP55ifv0FZiHVTfwovQCYp5+xN1u8Hg2/xt9AyXoP5cPsS+ir7PG+gT9hOr0jryE+Gm5bHXIr3jEy+N/RQp7jVPd6T3FvNPBDbTsu3fvTkG/6bOSzTWO3/P/ZfOFNFiAoF+DPn1wvX379tNyOB7WmsvInxqqZdrrfcW818mNte4S9D/Ljh9E3nX5uHp31M+CCvoVJ/P4Z0XTwb3c4eC+fPPmzQ87PMcjggqIedDBWNY3Avfu3Zve5DwKTPOqfDz9PvD6qi5N0L/iPX4l5x87xfzT00W96jGPe3MxjzsbK/tWoJzXn8ofQU4fH0P+Kmt79vr168chF7fDogT9M+RjzKd35i3+jEjUdzjwkR4h5pGmYS1zBKJ/YdzIXxA3zU/Qj6c4wgfX8l+XL8p/Xf485zeWa/oWiHDedhQ8HL9Q6bDjMz2qkkD5tPvvNb+26Ixlvz3++fn0/UCG/CXox7GXQ/pHOQw/tT4Fo/8XZmv/PZ4v5nsoe0Ytgajv0kf+oSyfZi3oRaIc0Ifl3fHvtX4DLLzv8P+VudCrq8vFvKtxWew1AlHeAH22vOmzQN+Xr24f9t35ZDF80CN+gJ2+AU351PsvPprkEoh41ioK+zR7RdzWt472XeO8O/94IgT98nL6DnDTN44J9Wvkv0sZahAbLUbMN4J0mzACgT6zOX2jrum7ww397lzQi0D5RgnT9ya+DPO75LgQ/8UZbSLr1yPm6+28MrZAgG8041Ptnx2Rod+hH7+t6/TX1CL+elu+QcJ3ERdmTfMFxHy+lSv7E2h8vqevN5p+EMuQ37f9qtMyetCflE+3/xr1t9HI35M46kyWrKvxB7slS93iWn9mvoVih/dodM7F/IqzMnTQo366/dOcStAfl//6fNbh7/Hhl9zog1wrdzFvJR/kuTufdzG/Zu7DBj3aV2le+ekT32gmyIerZcvY+YPbssVtf7WYb2/a7R3L2a/9WU8/qfKG0zFy0O+XT7f/Ffx3jj9HDz6gr5cn5p0NzHI3F6j08zCmd+W/lcU+99Xs149s5KBPP+c86hfE/T2xcoi/c4A3/5hT5YZiXoXVTTsVOP4gl+lrlO6fsYUp5P8qr3/m4+BpxZGDHum7w107KUE/fYgjXCHmEaZgDREFpr9NVNY1vYH6cWbcp79P/ur4jvyVkM+f6shBD/kNZb4e3fHbGb6aP1JX7i0g5nuLe17PAtM797L+6Sdafvpn2s6HiJd/Sr8Ph57313LtIwe99hdvbDJXQd+EsdpNxLwarRsTILBQQNAXgu19uaDvLT7/eWI+38qVBAjUFxD0+sZnPUHQz+Kr9mIxr0brxgQIrBQQ9JVwe71M0PeSnv8cMZ9v5UoCBPYTEPT9rFc9SdBXsVV7kZhXo3VjAgTOFBD0MwFrv1zQawvPv7+Yz7dyJQEC+wsI+v7mi54o6Iu4ql0s5tVo3ZgAgY0EBH0jyFq3EfRasvPvK+bzrVxJgEA7AUFvZz/ryYI+i6naRWJejdaNCRDYWEDQNwbd+naCvrXo/PuJ+XwrVxIg0F5A0NvP4MYVCHqbAYl5G3dPJUBgvYCgr7fb5ZWCvgvzFw8R8/3NPZEAgfMFBP18w6p3EPSqvN/cXMz39fY0AgS2ExD07Syr3EnQq7BeeVMx38/akwgQ2F5A0Lc33fSOgr4p57U3E/N9nD2FAIF6AoJez3aTOwv6Jow33kTM6xt7AgEC9QUEvb7xWU8Q9LP4Tr5YzE8SuYAAgU4EBD34oAS93oDEvJ6tOxMgsL+AoO9vvuiJgr6Ia/bFYj6byoUECHQiIOjBByXo2w9IzLc3dUcCBNoLCHr7Gdy4AkHfdkBivq2nuxEgEEdA0OPM4sqVCPp2AxLz7SzdiQCBeAKCHm8mX6xI0LcZkJhv4+guBAjEFRD0uLP5sDJBP39AYn6+oTsQIBBfQNCDz0jQzxuQmJ/n59UECPQjIOjBZyXo6wck5uvtvJIAgf4EBD34zAR93YDEfJ2bVxEg0K+AoAefnaAvH5CYLzfzCgIE+hcQ9OAzFPRlAxLzZV6uJkAgj4CgB5+loM8fkJjPt3IlAQL5BAQ9+EwFfd6AxHyek6sIEMgrIOjBZyvopwck5qeNXEGAQH4BQQ8+Y0G/eUBiHvwAWx4BArsJCPpu1OseJOjXu4n5ujPlVQQI5BQQ9OBzFfSrByTmwQ+u5REgsLuAoO9OvuyBgv6tl5gvO0OuJkBgDAFBDz5nQf9yQGIe/MBaHgECzQQEvRn9vAcL+j9OYj7vzLiKAIExBQQ9+NwF/eOAxDz4QbU8AgSaCwh68xHcvABBF/PgR9TyCBAIIiDoQQZx3TJGD7p35sEPqOURIBBGQNDDjOLqhYwcdDEPfjgtjwCBUAKCHmoc3y5m1KCLefCDaXkECIQTEPRwI/lyQSMGXcyDH0rLI0AgpICghxzLP4saLehiHvxAWh4BAmEFBD3saD4ubKSgi3nww2h5BAiEFhD00OMZJ+hiHvwgWh4BAuEFBD34iEZ4hy7mwQ+h5REg0IWAoAcfU/agi3nwA2h5BAh0IyDowUeVOehiHvzwWR4BAl0JCHrwcWUNupgHP3iWR4BAdwKCHnxkGYMu5sEPneURINClgKAHH1u2oIt58ANneQQIdCsg6MFHlynoYh78sFkeAQJdCwh68PFlCbqYBz9olkeAQPcCgh58hBmCLubBD5nlESCQQkDQg4+x96CLefADZnkECKQREPTgo+w56GIe/HBZHgECqQQEPfg4ew26mAc/WJZHgEA6AUEPPtIegy7mwQ+V5REgkFJA0IOPtbegi3nwA2V5BAikFRD04KPtKehiHvwwWR4BAqkFBD34eHsJupgHP0iWR4BAegFBDz7iHoIu5sEPkeURIDCEgKAHH3P0oIt58ANkeQQIDCMg6MFHHTnoYh788FgeAQJDCQh68HFHDbqYBz84lkeAwHACgh585BGDLubBD43lESAwpICgBx97tKCLefADY3kECAwrIOjBRx8p6GIe/LBYHgECQwsIevDxRwm6mAc/KJZHgMDwAoIe/AhECLqYBz8klkeAAIEiIOjBj0HroIt58ANieQQIEDgKCHrwo9Ay6GIe/HBYHgECBD4TEPTgx6FV0MU8+MGwPAIECHwlIOjBj0SLoIt58ENheQQIELhCQNCDH4u9gy7mwQ+E5REgQOAaAUEPfjT2DLqYBz8MlkeAAIEbBAQ9+PHYK+hiHvwgWB4BAgROCAh68COyR9DFPPghsDwCBAjMEBD0GUgtL6kddDFvOV3PJkCAwHYCgr6dZZU71Qy6mFcZmZsSIECgiYCgN2Gf/9BaQRfz+TNwJQECBHoQEPTgU6oRdDEPPnTLI0CAwAoBQV+BtudLtg66mO85Pc8iQIDAfgKCvp/1qidtGXQxXzUCLyJAgEAXAoIefExbBV3Mgw/a8ggQIHCmgKCfCVj75VsEXcxrT8n9CRAg0F5A0NvP4MYVnBt0MQ8+YMsjQIDARgKCvhFkrducE3QxrzUV9yVAgEA8AUGPN5MvVrQ26GIefLCWR4AAgY0FBH1j0K1vtyboYr71FNyPAAEC8QUEPfiMlgZdzIMP1PIIECBQSUDQK8FuddslQRfzrdTdhwABAv0JCHrwmc0NupgHH6TlESBAoLKAoFcGPvf2c4Iu5ucqez0BAgT6FxD04DM8FXQxDz5AyyNAgMBOAoK+E/Tax9wUdDFfq+p1BAgQyCcg6MFnel3QxTz44CyPAAECOwsI+s7gSx93VdDFfKmi6wkQIJBfQNCDz/jroIt58IFZHgECBBoJCHoj+LmP/TzoYj5XzXUECBAYT0DQg8/8U9DFPPigLI8AAQKNBQS98QBOPX4KernmcHFx8Wf53/unrk/w7w9lzz8cyq8Ee7EFAgQI7CYg6LtRr3vQFLcS86divs7PqwgQIDCKgKDHn/TbssQ78Zd59gq9Mz+b0A0IEBhZQNBHnn6cvYt5nFlYCQECnQoIeqeDS7RsMU80TFshQKCdgKC3s/fk8sV+vgDOMSBAgMA2AoK+jaO7LBcQ8+VmXkGAAIFrBQTd4WghIOYt1D2TAIHUAoKeerwhNyfmIcdiUQQI9C4g6L1PsK/1i3lf87JaAgQ6EhD0jobV+VLFvPMBWj4BArEFBD32fLKsTsyzTNI+CBAIKyDoYUeTZmFinmaUNkKAQGQBQY88nf7XJub9z9AOCBDoREDQOxlUh8sU8w6HZskECPQrIOj9zi7yysU88nSsjQCBlAKCnnKsTTcl5k35PZwAgVEFBH3UydfZt5jXcXVXAgQInBQQ9JNELpgpIOYzoVxGgACBGgKCXkN1vHuK+Xgzt2MCBIIJCHqwgXS4HDHvcGiWTIBAPgFBzzfTPXck5ntqexYBAgRuEBB0x2OtgJivlfM6AgQIVBAQ9AqoA9xSzAcYsi0SINCXgKD3Na8IqxXzCFOwBgIECHwlIOiOxBIBMV+i5VoCBAjsKCDoO2J3/igx73yAlk+AQG4BQc893612J+ZbSboPAQIEKgkIeiXYRLcV80TDtBUCBPIKCHre2W6xMzHfQtE9CBAgsIOAoO+A3OkjxLzTwVk2AQJjCgj6mHM/teu379+//7lcdDh1oX/fVuBQfrVdgacTIBBFQNCjTMI6CJwncLi4uHj17t27/5TbvCydf3ne7byaAIHeBAS9t4lZL4GZAiXwz0rg/+Vd/EwwlxHoXEDQOx+g5RM4JSDsp4T8ewI5BAQ9xxztgsBJgfJ1Eb+Ud+vPT17oAgIEuhQQ9C7HZtEE1glM79Zfv379eN2rvYoAgcgCgj6edvgAAAZVSURBVB55OtZGoI7Aqzdv3nxf59buSoBAKwFBbyXvuQTaCrwsUf+h7RI8nQCBLQUEfUtN9yLQl4Co9zUvqyVwo4CgOyAEBhYoXyj3uHyh3LOBCWydQBoBQU8zShshsEpg+q6A3/u76qvsvIhAKAFBDzUOiyHQRMCn3puweyiBbQUEfVtPdyPQpcD0vfvLu/QXXS7eogkQ+CAg6A4CAQK3yt9Pf17+fvovKAgQ6FdA0PudnZUT2FSgvEu/68/SNyV1MwK7Cgj6rtweRiCugK94jzsbKyMwR0DQ5yi5hsAAAuXT7i/Kp91/HmCrtkggpYCgpxyrTRFYJfC2fPe471a90osIEGguIOjNR2ABBOII+HP0OLOwEgJLBQR9qZjrCSQW8CNWEw/X1tILCHr6EdsggfkCvjBuvpUrCUQTEPRoE7EeAg0FBL0hvkcTOFNA0M8E9HICmQR8yj3TNO1lNIGRg/6o/DWdp6MN3H4J3CTgW8A6HwT6FRg56D+VoP/R7+isnMD2AsefvPZq+zu7IwECtQVGDvqdEvT/1gZ2fwI9Cfhraz1Ny1oJfCkwbNAnhrt3705Bv+NQECDwQeBV+cYy37MgQKBPgaGDfu/evd/LO5KHfY7OqglsK1A+Y/WsfOvXx9ve1d0IENhLYOigX15ePiwfxH7fC9tzCEQW8AVxkadjbQROC4we9OnP0d/4tPvpg+KK9AKH4xfEvU2/UxskkFRg6KBPMy2fdn9aPpA9Sjpf2yIwS8A3lJnF5CICoQWGD3r5tLuvdg99RC1uBwHvzndA9ggCtQWGD/oEXKL+pHzq/dfa2O5PIKKAd+cRp2JNBJYLCPrRrPwVtr/K/72/nNArCPQrUP5D9kX5yvaf+92BlRMg8ElA0I8S5V365fEL5JwOAqMI+FT7KJO2zyEEBP2zMZem3y9Rn96p+0Ugu8Db4w9ieZF9o/ZHYBQBQf9q0qI+ytEfep9iPvT4bT6rgKBfMVlRz3rc7asIiLljQCCpgKBfM9hj1KfvIucL5ZIe/gG39fL4afbDgHu3ZQLpBQT9xIhL2P3c9PS/DdJvcHpX/tvhcHiWfqc2SGBgAUGfMfzpK+Bv3779qx/kMgPLJZEEpq9i/3dZ0PMSc+/KI03GWghUEBD0hajHd+w/lpc9WPhSlxPYQ+BQ/qbGq3fv3k0hf1k67nuz76HuGQQCCAj6GUMocf+pvHz6eeqXZ9zGSwmcKzBF+9X0j4CfS+n1BPoVEPR+Z2flBAgQIEDgbwFBdxgIECBAgEACAUFPMERbIECAAAECgu4MECBAgACBBAKCnmCItkCAAAECBATdGSBAgAABAgkEBD3BEG2BAAECBAgIujNAgAABAgQSCAh6giHaAgECBAgQEHRngAABAgQIJBAQ9ARDtAUCBAgQICDozgABAgQIEEggIOgJhmgLBAgQIEBA0J0BAgQIECCQQEDQEwzRFggQIECAgKA7AwQIECBAIIGAoCcYoi0QIECAAAFBdwYIECBAgEACAUFPMERbIECAAAECgu4MECBAgACBBAKCnmCItkCAAAECBATdGSBAgAABAgkEBD3BEG2BAAECBAgIujNAgAABAgQSCAh6giHaAgECBAgQEHRngAABAgQIJBAQ9ARDtAUCBAgQICDozgABAgQIEEggIOgJhmgLBAgQIEBA0J0BAgQIECCQQEDQEwzRFggQIECAgKA7AwQIECBAIIGAoCcYoi0QIECAAAFBdwYIECBAgEACAUFPMERbIECAAAECgu4MECBAgACBBAKCnmCItkCAAAECBATdGSBAgAABAgkEBD3BEG2BAAECBAgIujNAgAABAgQSCAh6giHaAgECBAgQEHRngAABAgQIJBAQ9ARDtAUCBAgQICDozgABAgQIEEggIOgJhmgLBAgQIEBA0J0BAgQIECCQQEDQEwzRFggQIECAgKA7AwQIECBAIIGAoCcYoi0QIECAAAFBdwYIECBAgEACAUFPMERbIECAAAECgu4MECBAgACBBAKCnmCItkCAAAECBATdGSBAgAABAgkEBD3BEG2BAAECBAgIujNAgAABAgQSCAh6giHaAgECBAgQEHRngAABAgQIJBAQ9ARDtAUCBAgQICDozgABAgQIEEggIOgJhmgLBAgQIEBA0J0BAgQIECCQQOD/Ae+XuyGF5wwWAAAAAElFTkSuQmCC" alt=" ic_fluent_arrow_maximize_24_filled" />

**Comment by not-nef** [comment]
??

**Comment by sumeshir26** [comment]
![image](https://user-images.githubusercontent.com/68823982/151483111-00376ba9-7fc9-4b45-9d92-a2b872bf8f36.png)

**Comment by im-coder-lg** [comment]
Fluenticons? If yeah, then we could use a `command: lambda fullscreen` function and `def`ine it beforehand.

**Comment by not-nef** [comment]
Will definitely use that

**Comment by im-coder-lg** [comment]
Can we reopen this? You are supposed to close issues after PRs are merged, not when they are made. I'll reopen and use a GitHub symlink to close this issue on merge.

**Comment by not-nef** [comment]
Okay

**Comment by sumeshir26** [comment]
Fixed on master
