### ISSUE TITLE
Switch to win32mica

### ISSUE THREAD

**Issue by not-nef** [Futura-Py/TimerX#93]
Will do soon!

**Comment by rdbende** [comment]
Though you should also keep Acrylic for Win10, since Mica is Win11-only.

**Comment by not-nef** [comment]
Okay. I tested win32mica today and for some reason it didnt work. The instructions also aren't the best.

**Comment by rdbende** [comment]
You need Windows 11 build 22000 and above to be able to use the Mica effect.

**Comment by sumeshir26** [comment]
@rdbende build 22000(Currently Stable and Beta Channel- I'm on beta) has the undocumented mica which is not very customizable but, build 22523(Dev Channel) has a pulic mica api, which has a more reliable and customizable mica than 22000

**Comment by sumeshir26** [comment]
I started work on this here: https://github.com/Futura-Py/TimerX/tree/sumeshir26/mica
But I get a error. Does anyone know how to fix this?

**Comment by not-nef** [comment]
![image](https://user-images.githubusercontent.com/83908932/155267695-71cee5b7-2586-47bd-8051-ab5de9b05469.png)

Two tabspaces

**Comment by sumeshir26** [comment]
I know, fixing later

**Comment by im-coder-lg** [comment]
What's happened recently other than merges and reviews as well as this?
PS: I will be offline for a few days(expected to be two fortnights), since I must catch up to schoolwork as well as make a science project, do my final exams+attend bridge course for next year. Will help when free though.

**Comment by sumeshir26** [comment]
@im-coder-lg Not much, just work was started on mica support, and some code cleanup

**Comment by im-coder-lg** [comment]
Hmm, add a toggle for it. I think I don't need Mica since Windows Aero does my job. Also, can anyone add blur toggles with the functionality to show the incompatibility popup on unsupported systems?

**Comment by not-nef** [comment]
> Hmm, add a toggle for it. I think I don't need Mica since Windows Aero does my job. Also, can anyone add blur toggles with the functionality to show the incompatibility popup on unsupported systems?

Will add that after 1.1
