### ISSUE TITLE
setAlwaysOnTop() error on switching themes

### ISSUE THREAD

**Issue by im-coder-lg** [Futura-Py/TimerX#97]
**Describe the bug**
In Line 460:
https://github.com/Futura-Py/TimerX/blob/d18616cb5a15a20a5b3f51e50a33e33cae64a9a7/main.py#L460

It takes only one positional arg but two(`app`) were given. Luckily, I know a fix.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Terminal
2. Run TimerX via Python
3. Experience error 
**Expected behaviour**
Supposed to launch with no errors.

**Screenshots**
![hyuxn6K03d](https://user-images.githubusercontent.com/76845820/155838683-cacef7cb-c1f9-414b-ab56-b8752fe92dd9.gif)

**Desktop (please complete the following information):**

- OS: Raspbian Bullseye ARM64
- Version: Source Code

**Additional context**
I can fix this.

**Comment by im-coder-lg** [comment]
Only thing is, it seems so unrelated, but I fixed it on my Raspberry Pi. Wait, just getting it set up for pushing.

**Comment by not-nef** [comment]
Well just remove the parameter lmao. Its no big deal

**Comment by sumeshir26** [comment]
Why create  bug report for such a small bug? You cn commit these kinds of things directley

**Comment by im-coder-lg** [comment]
> Why create bug report for such a small bug? You cn commit these kinds of things directly

If I do that, I'd accidentally add bloatfiles.
